# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.1"
manifest_format = "2.0"
project_hash = "7eb8a735b8aba5390b460b3e6a1bb293d290a500"

[[deps.ParticleMeshEwald]]
path = "."
uuid = "cd47a632-4c33-49da-880f-bcc568aa1a40"
version = "1.0.0-DEV"
